---
count: 4
default:
  restart: 0
  wait: 0
editor:
  files:
    libdb:
      - lib/App/Wollemi/Schema.pm
      - lib/App/Wollemi/Schema/Result/*.pm
    main:
      - lib/App/Wollemi.pm
      - lib/App/Wollemi/Controller/*.pm
      - lib/App/Wollemi/Model/*.pm
      - lib/App/Wollemi/View/*.pm
name: wollemi
terminals:
  1a:
    command: plackup app_wollemi.psgi -p 4334
  2:
    edit: main
  3:
    edit: libdb
