=head1 NAME

DB Design

=head1 Design

Two options PostgreSQL or MongoDB.

=head2 PostgreSQL

User accounts more traditional
Can be done in a such a way as to be reasonably portable to other DB engines.
Tree queries.
BEM content will be text blobs (no easy searching)

=head2 MongoDB

The BEM data is a more natural fit for JSON
Ease in setup
Querying of deep data possible (not trivial)
history in same object?

=head1 What's needed

Store two types of BEM scripts:

=over 4

=item 1

"Type" scripts these are the boiler plates for actual data

=item 2

"Data" scripts represent the data that will be rendered as part of another
site's content.

=back

Each script will need filter filds

eg:

  path
  site
  device_type
  tags

=cut
