=head1 NAME

DB Design

=head1 Design

Two options PostgreSQL or MongoDB.

=head2 PostgreSQL

User accounts more traditional
Can be done to be reasonably portable to other DBs

=head2 MongoDB

The BEM data is a more natural fit for JSON
Ease in setup

=head1 What's needed

Store two types of BEM scripts:

=over 4

=item 1

"Type" scripts these are the boiler plates for actual data

=item 2

"Data" scripts represent the data that will be rendered as part of another
site's content.

=back


=cut
